// src/components/workout/WorkoutBlock.jsx — extracted from src/app.jsx (SPA-split Phase 3).
// React is a runtime global. Shared helpers/components imported below (freevars-driven).
import { SECTION_STYLES } from "../../lib/constants.js";
import { extractMainLabel } from "../../lib/format.js";
import { inferBlockZone, ZONES } from "../../lib/engine.js";
import { RoundRestRow } from "./RoundRestRow.jsx";
import { SetRow } from "./SetRow.jsx";

    const { useState, useMemo } = React;

    export function WorkoutBlock({ block, equipment, onRegenerate, regenError, blockIdx, openSwapKey, onToggleSwap, onApplySwap, editIntervalKey, editIntervalDraft, setEditIntervalDraft, editIntervalError, onStartEditInterval, onCommitInterval, onClearInterval, onCancelInterval, editDescKey, editDescDraft, setEditDescDraft, onStartEditDesc, onCommitDesc, onCancelDesc, isFavorited, onToggleFavorite, isDisfavorited, onToggleDisfavorite, isEngineDisfavorited, onToggleEngineDisfavor, isEngineFavorited, onToggleEngineFavorite, onRoundRestChange, unit = "yds", isPinned, onTogglePin, recentMainLabels, poolMode = "25y", sectionSource = "bank", onSectionSourceChange, advancedGenerate = true, favoriteSets, disfavorSets, onCycleSetStatus, isCoach = false, onSnapshot = null, ugcSetIdMeta = null }) {
      // UGC Phase C/D — derive whether this block was sourced from a UGC
      // overlay option, and which variant of the badge to show.
      // Look up the first matching set's metadata (all sets in an overlay
      // option share the same _is_own/_visibility so any hit answers it).
      let ugcMeta = null;
      if (ugcSetIdMeta && block && Array.isArray(block.sets)) {
        for (const s of block.sets) {
          if (s && s.id && ugcSetIdMeta.has(s.id)) {
            ugcMeta = ugcSetIdMeta.get(s.id);
            break;
          }
        }
      }
      const isUgcBlock = !!ugcMeta;
      const s = SECTION_STYLES[block.section];
      // Light header text (e.g. main set on dark slate) → use white-tinted button.
      // Dark header text → use dark-tinted button.
      const isDarkHeader = s.headerText === "#ffffff";
      const btnBg     = isDarkHeader ? "rgba(255,255,255,0.12)" : "rgba(15,23,42,0.06)";
      const btnHoverBg = isDarkHeader ? "rgba(255,255,255,0.20)" : "rgba(15,23,42,0.12)";
      const btnBorder = isDarkHeader ? "rgba(255,255,255,0.25)" : "rgba(15,23,42,0.15)";
      const [hovered, setHovered] = useState(false);
      // H: derive the block's effort-zone for the header pip; per-set pips
      // are shown only when a set diverges from this dominant zone.
      const blockZoneId = useMemo(() => inferBlockZone(block), [block]);
      const blockZone   = ZONES[blockZoneId] || ZONES.aerobic;
      return (
        <div className="workout-block" style={{ borderRadius: 12, border: isPinned ? `2px solid ${s.dot}` : `1px solid ${s.border}`, overflow: "hidden", marginBottom: 16 }}>
          <div className="workout-block-header" style={{ background: s.headerBg, color: s.headerText, padding: "12px 20px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
              <span style={{ width: 10, height: 10, borderRadius: "50%", background: s.dot, display: "inline-block" }} />
              <span style={{ fontWeight: 700, fontSize: 12, textTransform: "uppercase", letterSpacing: "0.1em" }}>{block.name}</span>
              {block.__engineMeta && (
                <span
                  title={`Generated by the SetForge engine (template: ${block.__engineMeta.template_id})`}
                  style={{
                    display: "inline-flex", alignItems: "center",
                    padding: "1px 7px", borderRadius: 999,
                    background: "rgba(245,158,11,0.18)",
                    border: "1px solid var(--color-warn)",
                    color: isDarkHeader ? "var(--color-warn)" : "#92400e",
                    fontSize: 10, fontWeight: 700, letterSpacing: "0.04em",
                  }}>
                  ⚡ ENGINE
                </span>
              )}
              {/* UGC Phase C/D — badge when block came from the UGC overlay.
                  Three variants based on ugcMeta (set in App-level walker):
                    📝 = your own (any visibility)
                    👥 = team-shared from another coach (Phase D)
                    🌐 = admin-approved public (Phase E — wired but quiet
                         until visibility='public' rows exist) */}
              {isUgcBlock && (() => {
                let icon, label, title;
                if (ugcMeta._is_own) {
                  icon = "📝"; label = "UGC"; title = "Your own UGC bank option (📝 My Sets)";
                } else if (ugcMeta._visibility === "team") {
                  icon = "👥"; label = "TEAM";  title = "Team-shared UGC from another coach on your team";
                } else if (ugcMeta._visibility === "public") {
                  icon = "🌐"; label = "PUBLIC"; title = "Public UGC option (admin-approved)";
                } else {
                  icon = "📝"; label = "UGC"; title = "UGC bank option";
                }
                return (
                  <span title={title}
                    style={{
                      display: "inline-flex", alignItems: "center",
                      padding: "1px 7px", borderRadius: 999,
                      background: "rgba(59,130,246,0.18)",
                      border: "1px solid var(--color-primary)",
                      color: isDarkHeader ? "var(--color-primary)" : "#1e40af",
                      fontSize: 10, fontWeight: 700, letterSpacing: "0.04em",
                    }}>
                    {icon} {label}
                  </span>
                );
              })()}
              <span className="screen-only"
                title={`Effort zone: ${blockZone.label}`}
                style={{
                  display: "inline-flex", alignItems: "center", gap: 4,
                  padding: "1px 7px", borderRadius: 999,
                  background: `${blockZone.color}22`,
                  border: `1px solid ${blockZone.color}`,
                  color: isDarkHeader ? "#fff" : blockZone.color,
                  fontSize: 10, fontWeight: 700, letterSpacing: "0.04em",
                  textTransform: "uppercase",
                }}>
                <span style={{ width: 6, height: 6, borderRadius: "50%", background: blockZone.color, display: "inline-block" }} />
                {blockZone.label}
              </span>
              {isPinned && <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.06em", opacity: 0.8 }}>PINNED</span>}
              {(() => {
                if (!recentMainLabels) return null;
                const lbl = extractMainLabel(block);
                if (!lbl) return null;
                const days = recentMainLabels.get(lbl);
                if (days === undefined) return null;
                return (
                  <span className="screen-only"
                    title={`You completed this main set ${days === 0 ? "today" : days === 1 ? "yesterday" : days + " days ago"}`}
                    style={{
                      fontSize: 10, fontWeight: 700, letterSpacing: "0.02em",
                      color: "#fca5a5", background: "rgba(127,29,29,0.45)",
                      border: "1px solid #7f1d1d",
                      padding: "1px 6px", borderRadius: 999,
                    }}>
                    last seen {days === 0 ? "today" : `${days}d ago`}
                  </span>
                );
              })()}
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              {/* S3 — per-section Bank | Engine | Mix toggle. Triggers a
                  regen of this section under the chosen source. Disabled
                  when section is pinned (pin wins). */}
              {onSectionSourceChange && !isPinned && advancedGenerate && (
                <div className="screen-only" style={{ display: "inline-flex", gap: 2, borderRadius: 6, background: btnBg, padding: 2, border: `1px solid ${btnBorder}` }}>
                  {["bank", "engine", "mix"].map(opt => {
                    const active = sectionSource === opt;
                    return (
                      <button
                        key={opt}
                        type="button"
                        onClick={() => onSectionSourceChange(opt)}
                        title={`Set this section's source to ${opt === "bank" ? "the bank (curated sets)" : opt === "engine" ? "the engine (template-generated)" : "mix (bank prefix + engine suffix)"}`}
                        style={{
                          fontSize: 10, fontWeight: 700, letterSpacing: "0.04em",
                          padding: "2px 8px", borderRadius: 4,
                          background: active ? (isDarkHeader ? "rgba(255,255,255,0.22)" : "rgba(15,23,42,0.18)") : "transparent",
                          color: s.headerText, opacity: active ? 1 : 0.6,
                          border: "none", cursor: "pointer", textTransform: "uppercase",
                        }}>
                        {opt}
                      </button>
                    );
                  })}
                </div>
              )}
              <span style={{ fontWeight: 600, fontSize: 13 }}>{block.totalYards.toLocaleString()} {unit}</span>
              {/* v1.3 — Tri-state label-status toggle. Behavior branches on
                  whether the block is bank-sourced or engine-sourced:
                  • Bank: [★ / — / 👎] targets `block.label` in fav/disfav tables
                  • Engine: [★ disabled / — / 👎] targets `block.__engineMeta`
                    (template_id, stroke) in engine_disfavorites — engine
                    doesn't support favorites (per v1.3 scope choice), and
                    favoriting a dynamic engine label wouldn't survive the
                    next generate anyway.
                  Mutex is server-side for bank, single-tag (no opposite) for
                  engine. */}
              {block.section === "main" && (block.label || block.__engineMeta) && (onToggleFavorite || onToggleDisfavorite || onToggleEngineDisfavor || onToggleEngineFavorite) && (() => {
                const isEngineBlock = !!block.__engineMeta;
                const segments = isEngineBlock
                  ? [
                      // v1.13 — ★ now active for engine blocks too. Targets
                      // (template_id, stroke) in engine_favorites (settings
                      // .extra) with 3× pick weight. Universal precedence:
                      // favorite wins over disfavor on the same tuple.
                      { id: "favorite", icon: "★",  active: !!isEngineFavorited, disabled: false,
                        title: `Favorite this template — pick "${block.__engineMeta.template_id}" + ${block.__engineMeta.stroke} more often (3× weight)`,
                        activeColor: "var(--color-warn)" },
                      { id: "neutral",  icon: "—",  active: !isEngineDisfavorited && !isEngineFavorited,
                        title: "Neutral — default engine template weight",
                        activeColor: s.headerText },
                      { id: "disfavor", icon: "👎", active: !!isEngineDisfavorited,
                        title: `Disfavor this template — pick "${block.__engineMeta.template_id}" + ${block.__engineMeta.stroke} less often (0.25× weight)`,
                        activeColor: "#ef4444" },
                    ]
                  : [
                      { id: "favorite", icon: "★",  active: isFavorited, disabled: false,
                        title: "Favorite — pick this more often (3× weight)",
                        activeColor: "var(--color-warn)" },
                      { id: "neutral",  icon: "—",  active: !isFavorited && !isDisfavorited, disabled: false,
                        title: "Neutral — default pick weight",
                        activeColor: s.headerText },
                      { id: "disfavor", icon: "👎", active: isDisfavorited, disabled: false,
                        title: "Disfavor — pick this less often (0.25× weight)",
                        activeColor: "#ef4444" },
                    ];
                return (
                  <div className="screen-only" data-tour="step-favorite-toggle" style={{
                    display: "inline-flex", gap: 2, borderRadius: 6,
                    background: btnBg, padding: 2, border: `1px solid ${btnBorder}`,
                  }}>
                    {segments.map(opt => (
                      <button
                        key={opt.id}
                        type="button"
                        disabled={opt.disabled}
                        onClick={() => {
                          if (opt.disabled) return;
                          if (isEngineBlock) {
                            // v1.13 — Engine: ★ targets engine_favorites,
                            // 👎 targets engine_disfavorites, — clears
                            // whichever was active. Mutex handled in the
                            // App-level toggle handlers (favorite-add
                            // strips disfavor and vice versa).
                            if (opt.id === "favorite" && !isEngineFavorited && onToggleEngineFavorite) {
                              onToggleEngineFavorite(block.__engineMeta);
                            } else if (opt.id === "disfavor" && !isEngineDisfavorited && onToggleEngineDisfavor) {
                              onToggleEngineDisfavor(block.__engineMeta);
                            } else if (opt.id === "neutral") {
                              if (isEngineFavorited && onToggleEngineFavorite) onToggleEngineFavorite(block.__engineMeta);
                              else if (isEngineDisfavorited && onToggleEngineDisfavor) onToggleEngineDisfavor(block.__engineMeta);
                            }
                          } else {
                            // Bank: target block.label in favorites/disfavorites
                            if (opt.id === "favorite" && !isFavorited && onToggleFavorite) {
                              onToggleFavorite(block.label);
                            } else if (opt.id === "disfavor" && !isDisfavorited && onToggleDisfavorite) {
                              onToggleDisfavorite(block.label);
                            } else if (opt.id === "neutral") {
                              if (isFavorited && onToggleFavorite) onToggleFavorite(block.label);
                              else if (isDisfavorited && onToggleDisfavorite) onToggleDisfavorite(block.label);
                            }
                          }
                        }}
                        title={opt.title}
                        style={{
                          fontSize: 14, lineHeight: 1,
                          cursor: opt.disabled ? "not-allowed" : "pointer",
                          padding: "3px 7px", borderRadius: 4,
                          background: opt.active
                            ? (isDarkHeader ? "rgba(255,255,255,0.22)" : "rgba(15,23,42,0.18)")
                            : "transparent",
                          color: opt.active ? opt.activeColor : s.headerText,
                          opacity: opt.disabled ? 0.25 : (opt.active ? 1 : 0.55),
                          border: "none",
                          transition: "background 0.15s, opacity 0.15s",
                        }}>
                        {opt.icon}
                      </button>
                    ))}
                  </div>
                );
              })()}
              {/* UGC Phase C — coach-only 📥 snapshot. Pre-fills the
                  UGC form with this block's section/label/sets so the
                  coach can save it to their own bank. */}
              {isCoach && onSnapshot && block.sets && block.sets.length > 0 && (
                <button
                  type="button"
                  className="screen-only"
                  onClick={() => onSnapshot(block)}
                  title="Save this set to your bank (📝 My Sets)"
                  style={{
                    background: btnBg, border: `1px solid ${btnBorder}`,
                    color: s.headerText, fontSize: 14, lineHeight: 1,
                    cursor: "pointer", padding: "4px 7px", borderRadius: 6,
                  }}>
                  📥
                </button>
              )}
              {onTogglePin && (
                <button
                  type="button"
                  className="screen-only"
                  onClick={() => onTogglePin(block.section)}
                  title={isPinned ? "Unpin — regenerate this section next time" : "Pin — keep this section on next generate"}
                  style={{
                    background: isPinned ? "rgba(255,255,255,0.20)" : btnBg,
                    border: `1px solid ${isPinned ? "rgba(255,255,255,0.45)" : btnBorder}`,
                    color: s.headerText, fontSize: 14, lineHeight: 1,
                    cursor: "pointer", padding: "4px 7px", borderRadius: 6,
                    transition: "background 0.15s",
                  }}>
                  {isPinned ? "📌" : "📍"}
                </button>
              )}
              {onRegenerate && !isPinned && (
                <button
                  type="button"
                  className="screen-only"
                  onClick={() => onRegenerate(block.section)}
                  onMouseEnter={() => setHovered(true)}
                  onMouseLeave={() => setHovered(false)}
                  title={`Regenerate ${block.name} only`}
                  aria-label={`Regenerate ${block.name}`}
                  style={{
                    display: "inline-flex", alignItems: "center", gap: 4,
                    padding: "4px 9px", borderRadius: 6,
                    background: hovered ? btnHoverBg : btnBg,
                    color: s.headerText, border: `1px solid ${btnBorder}`,
                    fontSize: 12, fontWeight: 600, cursor: "pointer",
                    lineHeight: 1, transition: "background 0.15s",
                  }}>
                  <span style={{ fontSize: 13 }}>🔄</span>
                  <span>Regenerate</span>
                </button>
              )}
            </div>
          </div>
          {regenError && (
            <div className="screen-only" role="alert" style={{
              background: "#fef2f2", borderBottom: `1px solid ${s.border}`,
              color: "#991b1b", fontSize: 12, padding: "8px 20px",
              display: "flex", alignItems: "center", gap: 8,
            }}>
              <span>⚠️</span>
              <span>{regenError}</span>
            </div>
          )}
          <div style={{ background: s.bg, overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ borderBottom: "1px solid #e2e8f0" }}>
                  {["Reps × Dist", "Total", "Description", "Interval", "Focus"].map(h => (
                    <th key={h} style={{ padding: "8px 16px", textAlign: "left", fontSize: 11, fontWeight: 600, color: "var(--color-text-muted)", textTransform: "uppercase", letterSpacing: "0.05em" }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {(() => {
                  const rounds = block.rounds || 1;
                  const rows = [];
                  // v1.1 — Mix mode renders sub-blocks with header dividers
                  // (per spec §7.3 "two labeled sub-blocks within one section
                  // header"). When block.subBlocks is present, each
                  // sub-block gets its own labeled divider row; sub-block
                  // sourced from engine carries __engineMeta and gets a ⚡
                  // badge on its divider.
                  const subBlocks = Array.isArray(block.subBlocks) && block.subBlocks.length
                    ? block.subBlocks
                    : [{ label: null, sets: block.sets, totalYards: block.totalYards }];
                  for (let r = 0; r < rounds; r++) {
                    if (rounds > 1) {
                      rows.push(
                        <tr key={`round-${r}`}>
                          <td colSpan={5} style={{ padding: "6px 16px", background: "var(--color-card)", borderTop: r > 0 ? "1px solid var(--color-border)" : undefined }}>
                            <span style={{ fontSize: 11, fontWeight: 700, color: "var(--color-primary-text)", textTransform: "uppercase", letterSpacing: "0.08em" }}>
                              Round {r + 1}
                            </span>
                          </td>
                        </tr>
                      );
                    }
                    subBlocks.forEach((sb, sbIdx) => {
                      // Render a sub-block divider row when there's >1 sub-block
                      if (subBlocks.length > 1 && sb.label) {
                        const isEngineSub = !!sb.__engineMeta;
                        rows.push(
                          <tr key={`r${r}-sb${sbIdx}`}>
                            <td colSpan={5} style={{ padding: "8px 16px", background: "#f1f5f9", borderTop: sbIdx > 0 ? "1px solid #cbd5e1" : undefined }}>
                              <span style={{ fontSize: 11, fontWeight: 700, color: "var(--color-text-muted)", textTransform: "uppercase", letterSpacing: "0.08em" }}>
                                {sb.label} ({sb.totalYards} {unit})
                              </span>
                              {isEngineSub && (
                                <span title={`Generated by the SetForge engine (template: ${sb.__engineMeta.template_id})`}
                                  style={{
                                    marginLeft: 8, padding: "1px 6px", borderRadius: 999,
                                    background: "rgba(245,158,11,0.18)",
                                    border: "1px solid var(--color-warn)",
                                    color: "#92400e",
                                    fontSize: 10, fontWeight: 700, letterSpacing: "0.04em",
                                  }}>
                                  ⚡ ENGINE
                                </span>
                              )}
                            </td>
                          </tr>
                        );
                      }
                      let cumulativeSetIdx = 0;
                      // Setidx for the SetRow keys: count sets across prior sub-blocks
                      // so editing intervals/descs (which use a "blockIdx-setIdx" key)
                      // still target the right set in block.sets (the flat-concat list).
                      for (let priorSb = 0; priorSb < sbIdx; priorSb++) {
                        cumulativeSetIdx += subBlocks[priorSb].sets.length;
                      }
                      sb.sets.forEach((set, i) => {
                        const flatIdx = cumulativeSetIdx + i;
                        rows.push(
                          <SetRow key={`${r}-sb${sbIdx}-${i}`} set={set} idx={flatIdx} equipment={equipment}
                            blockIdx={blockIdx} setIdx={flatIdx}
                            isSwapOpen={openSwapKey === `${blockIdx}-${flatIdx}`}
                            onToggleSwap={onToggleSwap} onApplySwap={onApplySwap}
                            isEditingInterval={editIntervalKey === `${blockIdx}-${flatIdx}`}
                            editIntervalDraft={editIntervalDraft}
                            setEditIntervalDraft={setEditIntervalDraft}
                            editIntervalError={editIntervalKey === `${blockIdx}-${flatIdx}` ? editIntervalError : null}
                            onStartEditInterval={onStartEditInterval}
                            onCommitInterval={onCommitInterval}
                            onClearInterval={onClearInterval}
                            onCancelInterval={onCancelInterval}
                            poolMode={poolMode}
                            isEditingDesc={editDescKey === `${blockIdx}-${flatIdx}`}
                            editDescDraft={editDescDraft}
                            setEditDescDraft={setEditDescDraft}
                            onStartEditDesc={onStartEditDesc}
                            onCommitDesc={onCommitDesc}
                            onCancelDesc={onCancelDesc}
                            unit={unit}
                            blockSection={block.section}
                            blockZoneId={blockZoneId}
                            isFavoriteSet={!!(set.id && favoriteSets && favoriteSets.has(set.id))}
                            isDisfavorSet={!!(set.id && disfavorSets && disfavorSets.has(set.id))}
                            onCycleSetStatus={onCycleSetStatus}
                          />
                        );
                      });
                    });
                    // Rest row between rounds (not after last round)
                    if (rounds > 1 && r < rounds - 1) {
                      rows.push(
                        <RoundRestRow key={`rest-${r}`}
                          restSecs={block.roundRestSecs ?? 30}
                          onChange={onRoundRestChange ? (v) => onRoundRestChange(blockIdx, v) : null}
                        />
                      );
                    }
                  }
                  return rows;
                })()}
              </tbody>
            </table>
          </div>
        </div>
      );
    }
